# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 
# pusher_secret: 
# stripe_api_key: 
# stripe_publishable_key: 
#
# production:
#   stripe_api_key: 
#   stripe_publishable_key: 
cloudinary_cloud_name: ""
cloudinary_api_key: ""
cloudinary_api_secret: ""
twitter_app_id: ""
twitter_app_secret: ""